const tipoCFE = {

    "101": "e-Ticket",
    "102": "Nota de Crédito de e-Ticket",
    "103": "Nota de Débito de e-Ticket",
    "111": "e-Factura",
    "112": "Nota de Crédito de e-Factura",
    "113": "Nota de Débito de e-Factura",
    "121": "e-Factura Exportación",
    "122": "Nota de Crédito de e-Factura Exportación",
    "123": "Nota de Débito de e-Factura Exportación",
    "124": "e-Remito de Exportación",
    "131": "e-Ticket Venta por Cuenta Ajena",
    "132": "Nota de Crédito de e-Ticket Venta por Cuenta Ajena",
    "133": "Nota de Débito de e-Ticket Venta por Cuenta Ajena",
    "141": "e-Factura Venta por Cuenta Ajena",
    "142": "Nota de Crédito de e-Factura Venta por Cuenta Ajena",
    "143": "Nota de Débito de e-Factura Venta por Cuenta Ajena",
    "181": "e-Remito",
    "182": "e-Resguardo",
    "201": "e-Ticket Contingencia",
    "202": "Nota de Crédito de e-Ticket Contingencia",
    "203": "Nota de Débito de e-Ticket Contingencia",
    "211": "e-Factura Contingencia",
    "212": "Nota de Crédito de e-Factura Contingencia",
    "213": "Nota de Débito de e-Factura Contingencia",
    "221": "e-Factura Exportación Contingencia",
    "222": "Exportación Contingencia Exportación Contingencia",
    "223": "Nota de Débito de e-Factura Exportación Contingencia",
    "224": "e-Remito de Exportación Contingencia",
    "231": "e-Ticket Venta por Cuenta Ajena Contingencia",
    "232": "Nota de Crédito de e-Ticket Venta por Cuenta Ajena Contingencia",
    "233": "Nota de Débito de e-Ticket Venta por Cuenta Ajena Contingencia",
    "241": "e-Factura Venta por Cuenta Ajena Contingencia",
    "242": "Nota de Crédito de e-Factura Venta por Cuenta Ajena Contingencia",
    "243": "Nota de Débito de e-Factura Venta por Cuenta Ajena Contingencia",
    "281": "e-Remito Contingencia",
    "282": "e-Resguardo Contingencia"
}

export { tipoCFE }